name: subtree

on: 
  push:
    branches:
      - "main"

jobs:
  push:
    name: Push subtrees
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: foo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "githubactionbot@franklinkim.de"
          git subtree push --prefix=packages/common https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/franklinkim/git-subtree-poc-common.git fork/project-a
